AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Slack Application.

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    CodeUri: slack_app/
    Environment:
      Variables:
        LOG_LEVEL: INFO

Parameters:
  SSMVerificationTokenName:
    Type: String
    Default: SLACK_APP_SLACK_SIGNING_SECRET
  SSMSecretName:
    Type: String
    Default: SLACK_APP_SLACK_SIGNING_SECRET
  ApiStageName:
    Type: String
    Default: dev
  QueueMaxReceiveCount:
    Type: Number
    Default: 2

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-api-gateway'
      StageName: !Ref ApiStageName

  SlashCommandTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-slash-command'
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt SlashCommandQueue.Arn

  SlackAppTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-slack-app'
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt SlackAppQueue.Arn

  SlashCommandQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-slash-command-queue'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref QueueMaxReceiveCount

  SlackAppQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-slack-app-queue'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref QueueMaxReceiveCount

  QueuesPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SlashCommandQueue
        - !Ref SlackAppQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt SlashCommandQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Ref SlashCommandTopic
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt SlackAppQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Ref SlackAppTopic

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-dlq'

  SlackAppHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-slack-handler'
      Handler: app.slack_app_handler
      Environment:
        Variables:
          SSM_VERIFICATION_TOKEN_NAME: !Ref SSMVerificationTokenName
          SSM_SECRET_NAME: !Ref SSMSecretName
          SLASH_COMMAND_TOPIC_ARN: !Ref SlashCommandTopic
          SLACK_APP_TOPIC_ARN: !Ref SlackAppTopic
      Policies:
        - AmazonSSMReadOnlyAccess
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SlashCommandTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SlackAppTopic.TopicName
      Events:
        SlackApp:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /action-endpoint
            Method: post
        SlashCommand:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /slash-command
            Method: post

  SlashCommandWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-slash-command-worker'
      Handler: app.slash_command_worker
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt SlashCommandQueue.QueueName
      Events:
        QueueMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Queue: !GetAtt SlashCommandQueue.Arn

  SlackAppWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-slack-app-worker'
      Handler: app.slash_command_worker
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt SlackAppQueue.QueueName
      Events:
        QueueMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Queue: !GetAtt SlackAppQueue.Arn


Outputs:
  ApiGatewaySlashCommand:
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/slash-command/'
  ApiGatewaySlackApp:
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/action-endpoint/'
