AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Slack Application.

Globals:
  Function:
    Timeout: 3
    Runtime: python3.7
    CodeUri: slack_app/
    Environment:
      Variables:
        LOG_LEVEL: INFO
        QUEUE_URL: !Ref SlackAppQueue

Resources:
  SlackAppApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Slack App Api Gateway
      StageName: Production
  SlackAppQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SlackAppQueue
  SlackAppSlashCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.slash_command_handler
      Events:
        SlackApp:
          Type: Api
          Properties:
            RestApiId: !Ref SlackAppApiGateway
            Path: /slash-command
            Method: post
  SlackAppEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.slack_event_handler
      Events:
        SlackApp:
          Type: Api
          Properties:
            RestApiId: !Ref SlackAppApiGateway
            Path: /action-endpoint
            Method: post
  SlackAppQueueWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.queue_worker
      Events:
        SlackAppQueueMessage:
          Type: SQS
          Properties:
            BatchSize: 1
            Queue: !GetAtt SlackAppQueue.Arn

Outputs:
  SlackAppApiGatewaySlashCommand:
    Value: !Sub 'https://${SlackAppApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Production/slash-command/'
  SlackAppApiGatewayEvent:
    Value: !Sub 'https://${SlackAppApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Production/action-endpoint/'
  SlackAppQueueUrl:
    Value: !Ref SlackAppQueue
  SlackAppQueueARN:
    Value: !GetAtt SlackAppQueue.Arn
